#ifndef SAIS16
#define SAIS16

#include <sais2.h>

// Code generated by go generate; DO NOT EDIT.

/*func*/void text_16(unsigned char *text, int16_t *sa, int tLen, int sLen);

/*func*/void sais_8_16(unsigned char *text, int textMax, int16_t *sa, int16_t *tmp, int textLen, int saLen, int tmpLen);

/*func*/void sais_16(int16_t *text, int textMax, int16_t *sa, int16_t *tmp, int textLen, int saLen, int tmpLen);

/*func*/int16_t *freq_8_16(unsigned char *text, int16_t *freq, int16_t *bucket, int tLen);

/*func*/int16_t *freq_16(int16_t *text, int16_t *freq, int16_t *bucket, int tLen);

/*func*/void bucketMin_8_16(unsigned char *text, int16_t *freq, int16_t *bucket, int tLen);

/*func*/void bucketMin_16(int16_t *text, int16_t *freq, int16_t *bucket, int tLen);

/*func*/void bucketMax_8_16(unsigned char *text, int16_t *freq, int16_t *bucket, int tLen);

/*func*/void bucketMax_16(int16_t *text, int16_t *freq, int16_t *bucket, int tLen);

/*func*/int placeLMS_8_16(unsigned char *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen);

/*func*/int placeLMS_16(int16_t *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen);

/*func*/void induceSubL_8_16(unsigned char *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void induceSubL_16(int16_t *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void induceSubS_8_16(unsigned char *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void induceSubS_16(int16_t *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void length_8_16(unsigned char *text, int16_t *sa, int numLMS, int tLen);

/*func*/void length_16(int16_t *text, int16_t *sa, int numLMS, int tLen);

/*func*/int assignID_8_16(unsigned char *text, int16_t *sa, int textLen, int numLMS, int saLen);

/*func*/int assignID_16(int16_t *text, int16_t *sa, int textLen, int numLMS, int saLen);

/*func*/void map_16(int16_t *sa, int numLMS, int saLen);

/*func*/void recurse_16(int16_t *sa, int16_t *oldTmp, int numLMS, int maxID, int saLen, int tmpLen);

/*func*/void unmap_8_16(unsigned char *text, int16_t *sa, int numLMS, int tLen, int saLen);

/*func*/void unmap_16(int16_t *text, int16_t *sa, int numLMS, int tLen, int saLen);

/*func*/void expand_8_16(unsigned char *text, int16_t *freq, int16_t *bucket_8_64, int16_t *sa, int numLMS, int tLen, int saLen);

/*func*/void expand_16(int16_t *text, int16_t *freq, int16_t *bucket_8_64, int16_t *sa, int numLMS, int tLen, int saLen);

/*func*/void induceL_8_16(unsigned char *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void induceL_16(int16_t *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void induceS_8_16(unsigned char *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

/*func*/void induceS_16(int16_t *text, int16_t *sa, int16_t *freq, int16_t *bucket, int tLen, int saLen);

#endif