# CMake function to embed HIP source files as C++ string literals
# This is needed for HIPRTC (Runtime Compilation) which doesn't have filesystem access

# Usage:
#   embed_hip_sources(
#       OUTPUT_FILE "${PROJECT_BINARY_DIR}/generated/embedded_headers.hpp"
#       SOURCES file1.hip file2.hip.inc
#       [NAMESPACE hip_embedded]      # Optional, defaults to hip_embedded
#       [NO_MANIFEST]                 # Optional, skip generating the ALL_SOURCES array
#       [MANIFEST_NAME XELIS_SOURCES] # Optional, custom name for the manifest array
#   )


function(embed_hip_sources)
    # Parse arguments
    cmake_parse_arguments(
        EMBED                           # Prefix
        "NO_MANIFEST"                   # Options
        "OUTPUT_FILE;NAMESPACE;MANIFEST_NAME"  # Single-value args
        "SOURCES"                       # Multi-value args
        ${ARGN}
    )

    if(NOT EMBED_OUTPUT_FILE)
        message(FATAL_ERROR "embed_hip_sources: OUTPUT_FILE is required")
    endif()

    if(NOT EMBED_SOURCES)
        message(FATAL_ERROR "embed_hip_sources: SOURCES is required")
    endif()

    # Default namespace
    if(NOT EMBED_NAMESPACE)
        set(EMBED_NAMESPACE "hip_embedded")
    endif()

    # Default manifest name based on output file
    if(NOT EMBED_MANIFEST_NAME AND NOT EMBED_NO_MANIFEST)
        get_filename_component(OUTPUT_BASENAME "${EMBED_OUTPUT_FILE}" NAME_WE)
        string(TOUPPER "${OUTPUT_BASENAME}" EMBED_MANIFEST_NAME)
        string(REPLACE "-" "_" EMBED_MANIFEST_NAME "${EMBED_MANIFEST_NAME}")
    endif()

    # Start building the output content
    set(EMBEDDED_CONTENT "// Auto-generated by embed_hip_sources.cmake\n")
    set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}// DO NOT EDIT - this file is generated at build time\n\n")
    set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}#pragma once\n")
    set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}#include <string_view>\n\n")
    set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}namespace ${EMBED_NAMESPACE} {\n\n")

    # Track all variable names for the manifest
    set(ALL_VAR_NAMES "")
    set(SOURCE_COUNT 0)

    # Tell CMake to reconfigure if any of these source files change
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${EMBED_SOURCES})

    foreach(SOURCE_FILE ${EMBED_SOURCES})
        # Resolve to absolute path
        get_filename_component(ABS_SOURCE_FILE "${SOURCE_FILE}" ABSOLUTE)

        # Check file exists
        if(NOT EXISTS "${ABS_SOURCE_FILE}")
            message(FATAL_ERROR "embed_hip_sources: Source file not found: ${ABS_SOURCE_FILE}")
        endif()

        # Mark this file as a dependency so CMake reconfigures if it changes
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ABS_SOURCE_FILE}")

        # Read the file content
        file(READ "${ABS_SOURCE_FILE}" FILE_CONTENT)

        # Get relative path from project root for the include name
        file(RELATIVE_PATH REL_PATH "${PROJECT_SOURCE_DIR}" "${ABS_SOURCE_FILE}")

        # Create a valid C++ identifier from the path
        # Replace: / -> _  . -> _  - -> _
        string(REPLACE "/" "_" VAR_NAME "${REL_PATH}")
        string(REPLACE "." "_" VAR_NAME "${VAR_NAME}")
        string(REPLACE "-" "_" VAR_NAME "${VAR_NAME}")
        string(TOUPPER "${VAR_NAME}" VAR_NAME)

        # Track this variable
        list(APPEND ALL_VAR_NAMES "${VAR_NAME}")
        math(EXPR SOURCE_COUNT "${SOURCE_COUNT} + 1")

        # Append to embedded content using raw string literal
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}// Source: ${REL_PATH}\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}constexpr std::string_view ${VAR_NAME}_SOURCE = R\"EMBEDSRC(\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}${FILE_CONTENT}")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}\n)EMBEDSRC\";\n\n")

        # Store the path for runtime reference
        # For .inc header files, use just the basename so #include "file.inc" works
        # For .hip source files, use the full path
        string(REGEX MATCH "\\.inc$" IS_INC_FILE "${REL_PATH}")

        if(IS_INC_FILE)
            get_filename_component(FILE_BASENAME "${REL_PATH}" NAME)
            set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}constexpr std::string_view ${VAR_NAME}_PATH = \"${FILE_BASENAME}\";\n\n")
            message(STATUS "  -> Using basename for HIPRTC header: ${FILE_BASENAME}")
        else()
            set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}constexpr std::string_view ${VAR_NAME}_PATH = \"${REL_PATH}\";\n\n")
            message(STATUS "  -> Using full path for source: ${REL_PATH}")
        endif()

        message(STATUS "Embedding HIP source: ${REL_PATH} -> ${VAR_NAME}")
    endforeach()

    # Optionally create a manifest struct for this file's sources
    if(NOT EMBED_NO_MANIFEST)
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}// Manifest of embedded sources in this file\n")
        
        # Define EmbeddedSource struct only once using include guard
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}#ifndef HIP_EMBEDDED_SOURCE_STRUCT_DEFINED\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}#define HIP_EMBEDDED_SOURCE_STRUCT_DEFINED\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}struct EmbeddedSource {\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}    std::string_view path;\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}    std::string_view source;\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}};\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}#endif // HIP_EMBEDDED_SOURCE_STRUCT_DEFINED\n\n")

        # Build the manifest array with custom name
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}constexpr EmbeddedSource ${EMBED_MANIFEST_NAME}[] = {\n")
        foreach(VAR_NAME ${ALL_VAR_NAMES})
            set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}    {${VAR_NAME}_PATH, ${VAR_NAME}_SOURCE},\n")
        endforeach()
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}};\n\n")
        set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}constexpr size_t ${EMBED_MANIFEST_NAME}_COUNT = ${SOURCE_COUNT};\n\n")
    endif()

    set(EMBEDDED_CONTENT "${EMBEDDED_CONTENT}} // namespace ${EMBED_NAMESPACE}\n")

    # Ensure output directory exists
    get_filename_component(OUTPUT_DIR "${EMBED_OUTPUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}")

    # Write the output file
    file(WRITE "${EMBED_OUTPUT_FILE}" "${EMBEDDED_CONTENT}")

    message(STATUS "Generated embedded headers file: ${EMBED_OUTPUT_FILE} (${SOURCE_COUNT} sources)")

    # Create a custom command to regenerate the embedded headers when sources change
    add_custom_command(
        OUTPUT "${EMBED_OUTPUT_FILE}"
        COMMAND ${CMAKE_COMMAND} -E cmake_echo_color --cyan "Regenerating embedded HIP sources: ${EMBED_OUTPUT_FILE}"
        COMMAND ${CMAKE_COMMAND} -E touch "${EMBED_OUTPUT_FILE}"
        DEPENDS ${EMBED_SOURCES}
        COMMENT "Checking embedded HIP sources for changes"
        VERBATIM
    )
endfunction()